version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fastapi_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/test?charset=utf8
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend  # 로컬 파일 시스템을 컨테이너에 마운트
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./frontend:/app  # 로컬 파일 시스템을 컨테이너에 마운트
    environment:
      - CHOKIDAR_USEPOLLING=true  # 파일 변경 감지를 위한 설정

volumes:
  db_data:

networks:
  app_network:
    driver: bridge